apiVersion: v1
kind: Service
metadata:
  name: {{ template "heartbeat-chart.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP  # Change this if needed (NodePort, LoadBalancer, etc.)
  ports:
    - port: 5066
      targetPort: 5066
      protocol: TCP
      name: http
  selector:
    app: {{ template "heartbeat-chart.name" . }}
