on:
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          tag_prefix: "v2"
          release_name: "Release <RELEASE_VERSION>"
          bump_version_scheme: minor
          use_github_release_notes: true